version: '2'
services:
  nginx:
    image: evild/alpine-nginx:latest
    links:
      - php
    ports:
      - 80:80
      - 443:443
    volumes:
      - rutorrent-data-test:/rutorrent:ro
      - ./etc/nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:ro
  php:
    image: rutorrent
    volumes:
      - rutorrent-data-test:/rutorrent
volumes:
  rutorrent-data-test:
    driver: local
