version: '2'
services:
  nginx:
    image: evild/alpine-nginx:latest
    links:
      - php
    ports:
      - 80:80
      - 443:443
    volumes:
      - rutorrent-data:/rutorrent:ro
      - ./etc/nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:ro
  rutorrent:
    image: evild/rutorrent
    volumes:
      - rutorrent-data:/rutorrent
    ports:
      - 51413:51413
volumes:
  rutorrent-data:
    driver: local
